import type { ComponentType } from 'react';
import {
  Home,
  Users,
  Calendar,
  Briefcase,
  DollarSign,
  Building2,
  Award,
  BarChart2,
  ClipboardList,
  Shield,
  Settings,
  UserCircle,
  ScrollText,
  ArrowUpDown,
  Target,
  UserPlus,
  GraduationCap,
  Package,
  Receipt,
  Clock,
  FileText,
  Network,
  Wallet,
  FileBarChart,
  UserMinus,
  BookOpen,
  MessageSquare,
  Timer,
  Handshake,
  MapPin,
  PieChart,
  LayoutDashboard,
} from 'lucide-react';
import { Permission } from '@hrplatform/shared';

export interface NavItem {
  name: string;
  /** i18n translation key (dot-notation). Falls back to `name` if not translated. */
  nameKey?: string;
  href: string;
  icon: ComponentType<{ className?: string }>;
  /** If true, visible to all authenticated users regardless of permissions */
  alwaysVisible?: boolean;
  /** User must have ANY of these permissions to see this item */
  requiredPermissions?: Permission[];
  /** Feature that must be enabled for this nav item to appear */
  requiredFeature?: string;
}

export const navigation: NavItem[] = [
  {
    name: 'Dashboard',
    nameKey: 'nav.dashboard',
    href: '/dashboard',
    icon: Home,
    alwaysVisible: true,
  },
  {
    name: 'Employees',
    nameKey: 'nav.employees',
    href: '/employees',
    icon: Users,
    requiredPermissions: [Permission.VIEW_EMPLOYEES, Permission.MANAGE_EMPLOYEES],
    requiredFeature: 'EMPLOYEES',
  },
  {
    name: 'Departments',
    nameKey: 'nav.departments',
    href: '/departments',
    icon: Building2,
    requiredPermissions: [Permission.VIEW_DEPARTMENTS, Permission.MANAGE_DEPARTMENTS],
    requiredFeature: 'DEPARTMENTS',
  },
  {
    name: 'Designations',
    nameKey: 'nav.designations',
    href: '/designations',
    icon: Award,
    requiredPermissions: [Permission.VIEW_DESIGNATIONS, Permission.MANAGE_DESIGNATIONS],
    requiredFeature: 'DESIGNATIONS',
  },
  {
    name: 'Attendance',
    nameKey: 'nav.attendance',
    href: '/attendance',
    icon: Calendar,
    requiredPermissions: [Permission.VIEW_ATTENDANCE, Permission.MARK_ATTENDANCE, Permission.MANAGE_ATTENDANCE],
    requiredFeature: 'ATTENDANCE',
  },
  {
    name: 'Leave',
    nameKey: 'nav.leave',
    href: '/leave',
    icon: Briefcase,
    requiredPermissions: [Permission.VIEW_LEAVES, Permission.APPLY_LEAVE, Permission.MANAGE_LEAVES],
    requiredFeature: 'LEAVE',
  },
  {
    name: 'Leave Balance',
    nameKey: 'nav.leaveBalance',
    href: '/leave/balance',
    icon: ClipboardList,
    requiredPermissions: [Permission.VIEW_LEAVES, Permission.APPLY_LEAVE, Permission.MANAGE_LEAVES],
    requiredFeature: 'LEAVE',
  },
  {
    name: 'Payroll',
    nameKey: 'nav.payroll',
    href: '/payroll',
    icon: DollarSign,
    requiredPermissions: [Permission.VIEW_PAYROLL, Permission.VIEW_OWN_PAYROLL, Permission.MANAGE_PAYROLL],
    requiredFeature: 'PAYROLL',
  },
  {
    name: 'Salary Structures',
    nameKey: 'nav.salaryStructures',
    href: '/payroll/salary-structures',
    icon: ClipboardList,
    requiredPermissions: [Permission.MANAGE_PAYROLL],
    requiredFeature: 'PAYROLL',
  },
  {
    name: 'My Payslips',
    nameKey: 'nav.myPayslips',
    href: '/payroll/my-payslips',
    icon: Wallet,
    requiredPermissions: [Permission.VIEW_OWN_PAYROLL],
    requiredFeature: 'PAYROLL',
  },
  {
    name: 'Compliance Reports',
    nameKey: 'nav.complianceReports',
    href: '/payroll/reports',
    icon: FileBarChart,
    requiredPermissions: [Permission.MANAGE_PAYROLL, Permission.GENERATE_REPORTS],
    requiredFeature: 'PAYROLL',
  },
  {
    name: 'Reports',
    nameKey: 'nav.reports',
    href: '/reports',
    icon: BarChart2,
    requiredPermissions: [Permission.VIEW_REPORTS, Permission.GENERATE_REPORTS],
    requiredFeature: 'REPORTS',
  },
  {
    name: 'Performance',
    nameKey: 'nav.performance',
    href: '/performance',
    icon: Target,
    requiredPermissions: [Permission.VIEW_PERFORMANCE, Permission.MANAGE_PERFORMANCE, Permission.VIEW_OWN_PERFORMANCE],
    requiredFeature: 'PERFORMANCE',
  },
  {
    name: 'Recruitment',
    nameKey: 'nav.recruitment',
    href: '/recruitment',
    icon: UserPlus,
    requiredPermissions: [Permission.VIEW_RECRUITMENT, Permission.MANAGE_RECRUITMENT],
    requiredFeature: 'RECRUITMENT',
  },
  {
    name: 'Training',
    nameKey: 'nav.training',
    href: '/training',
    icon: GraduationCap,
    requiredPermissions: [Permission.VIEW_TRAINING, Permission.MANAGE_TRAINING, Permission.ENROLL_TRAINING],
    requiredFeature: 'TRAINING',
  },
  {
    name: 'Assets',
    nameKey: 'nav.assets',
    href: '/assets',
    icon: Package,
    requiredPermissions: [Permission.VIEW_ASSETS, Permission.MANAGE_ASSETS],
    requiredFeature: 'ASSETS',
  },
  {
    name: 'Expenses',
    nameKey: 'nav.expenses',
    href: '/expenses',
    icon: Receipt,
    requiredPermissions: [Permission.VIEW_EXPENSES, Permission.MANAGE_EXPENSES, Permission.SUBMIT_EXPENSE],
    requiredFeature: 'EXPENSES',
  },
  {
    name: 'Shifts',
    nameKey: 'nav.shifts',
    href: '/shifts',
    icon: Clock,
    requiredPermissions: [Permission.VIEW_SHIFTS, Permission.MANAGE_SHIFTS],
    requiredFeature: 'SHIFTS',
  },
  {
    name: 'Policies',
    nameKey: 'nav.policies',
    href: '/policies',
    icon: FileText,
    requiredPermissions: [Permission.VIEW_POLICIES, Permission.MANAGE_POLICIES, Permission.ACKNOWLEDGE_POLICY],
    requiredFeature: 'POLICIES',
  },
  {
    name: 'Offboarding',
    nameKey: 'nav.offboarding',
    href: '/offboarding',
    icon: UserMinus,
    requiredPermissions: [Permission.VIEW_OFFBOARDING, Permission.MANAGE_OFFBOARDING],
    requiredFeature: 'OFFBOARDING',
  },
  {
    name: 'Directory',
    nameKey: 'nav.directory',
    href: '/directory',
    icon: BookOpen,
    requiredPermissions: [Permission.VIEW_DIRECTORY],
    requiredFeature: 'DIRECTORY',
  },
  {
    name: 'Social Feed',
    nameKey: 'nav.socialFeed',
    href: '/social',
    icon: MessageSquare,
    requiredPermissions: [Permission.VIEW_DIRECTORY, Permission.SEND_KUDOS],
    requiredFeature: 'DIRECTORY',
  },
  {
    name: 'Surveys',
    nameKey: 'nav.surveys',
    href: '/surveys',
    icon: ClipboardList,
    requiredPermissions: [Permission.MANAGE_SURVEYS, Permission.RESPOND_SURVEY],
    requiredFeature: 'SURVEYS',
  },
  {
    name: 'Timesheets',
    nameKey: 'nav.timesheets',
    href: '/timesheets',
    icon: Timer,
    requiredPermissions: [Permission.MANAGE_TIMESHEETS, Permission.VIEW_OWN_TIMESHEETS],
    requiredFeature: 'TIME_TRACKING',
  },
  {
    name: 'Contractors',
    nameKey: 'nav.contractors',
    href: '/contractors',
    icon: Handshake,
    requiredPermissions: [Permission.VIEW_CONTRACTORS, Permission.MANAGE_CONTRACTORS],
    requiredFeature: 'CONTRACTORS',
  },
  {
    name: 'Analytics',
    nameKey: 'nav.analytics',
    href: '/analytics',
    icon: PieChart,
    requiredPermissions: [Permission.VIEW_ANALYTICS],
    requiredFeature: 'ANALYTICS',
  },
  {
    name: 'Org Chart',
    nameKey: 'nav.orgChart',
    href: '/org-chart',
    icon: Network,
    requiredPermissions: [Permission.VIEW_DEPARTMENTS, Permission.VIEW_EMPLOYEES],
    requiredFeature: 'DEPARTMENTS',
  },
  {
    name: 'Users',
    nameKey: 'nav.users',
    href: '/users',
    icon: Shield,
    requiredPermissions: [Permission.VIEW_USERS, Permission.MANAGE_USERS],
  },
  {
    name: 'Import/Export',
    nameKey: 'nav.importExport',
    href: '/import-export',
    icon: ArrowUpDown,
    requiredPermissions: [Permission.VIEW_EMPLOYEES, Permission.MANAGE_EMPLOYEES],
  },
  {
    name: 'Audit Logs',
    nameKey: 'nav.auditLogs',
    href: '/audit-logs',
    icon: ScrollText,
    requiredPermissions: [Permission.VIEW_AUDIT_LOGS],
    requiredFeature: 'AUDIT_LOGS',
  },
  {
    name: 'Settings',
    nameKey: 'nav.settings',
    href: '/settings',
    icon: Settings,
    requiredPermissions: [Permission.MANAGE_COMPANY],
  },
  {
    name: 'Profile',
    nameKey: 'nav.profile',
    href: '/profile',
    icon: UserCircle,
    alwaysVisible: true,
  },
];
